#imports
import scraperwiki
import lxml.html
import urlparse


def obtener_resultado(url):
    starting_url = urlparse.urljoin(base_url, url)
    html = scraperwiki.scrape(starting_url)
    root = lxml.html.fromstring(html)
    rev = root.cssselect("rev")
    print lxml.html.tostring(rev[0])
    for ref in rev[0].cssselect("ref"):
        print ref.text



def test():
    l = list()
    l.append("A. Dufresnes")
    l.append("A. Murphy")
    l.append("A. de la Tour Chambly")
    l.append("Abbott Liebling")
    l.append("Abraham Lincoln")
    l.append("Achile Tournier")
    l.append("Achille Chavée")
    l.append("Adam Smith")
    l.append("Adelaida García Morales")
    l.append("Adolf Hitler")
    l.append("Adolfo Bioy Casares")
    l.append("Adolfo Marsillach")
    l.append("Adolphe Thiers")
    l.append("Agatha Christie")
    l.append("Agatón")
    l.append("Agustín García Calvo")
    l.append("Alain")
    l.append("Alain Touraine")
    l.append("Alan Turing")
    l.append("Albert Camus")
    l.append("Albert Einstein")
    l.append("Albert Guinon")
    l.append("Albert Pike")
    l.append("Albert Schweitzer")
    l.append("Alberto Durero")
    l.append("Alberto Lleras Camargo")
    l.append("Alberto Moravia")
    l.append("Aldous Huxley")
    l.append("Alec Guinnes")
    l.append("Alejandro Casona")
    l.append("Alejandro Dumas")
    l.append("Alejandro Dumas (hijo)")
    l.append("Alejandro Gándara")
    l.append("Alejandro Vinet")
    l.append("Alejo Carpentier")
    l.append("Aleksandr Isayevich Solzhenitsin")
    l.append("Alessandro Manzoni")
    l.append("Alessandro Pertini")
    l.append("Alexander Hamilton")
    l.append("Alexander Hubbleton")
    l.append("Alexander Pope")
    l.append("Alexandre Graham Bell")
    l.append("Alexei Tolstoi")
    l.append("Alexis Carrel")
    l.append("Alexis Tocqueville")
    l.append("Alfonso Guerra")
    l.append("Alfonso Martínez de Toledo")
    l.append("Alfonso Reyes")
    l.append("Alfonso Rodríguez Castelao")
    l.append("Alfonso V el Magnánimo")
    l.append("Alfonso X el Sabio")
    l.append("Alfred Adler")
    l.append("Alfred Emanuel Smith")
    l.append("Alfred Hitchcock")
    l.append("Alfred North Whitehead")
    l.append("Alfred Tennyson")
    l.append("Alfred Victor de Vigny")
    l.append("Alfred d' Houdetot")
    l.append("Alfredo Bryce Echenique")
    l.append("Alfredo Conde")
    l.append("Alfredo Landa")
    l.append("Alisa Kwitney")
    l.append("Alonso de Ercilla y Zúñiga")
    l.append("Alonso de la Torre")
    l.append("Alphonse Allais")
    l.append("Alphonse Daudet")
    l.append("Alphonse de Lamartine")
    l.append("Amado Nervo")
    l.append("Amauri Pérez")
    l.append("Ambrose Bierce")
    l.append("Amintore Fanfani")
    l.append("Amos Bronson Alcott")
    l.append("Amélie Nothomb")
    l.append("Ana Diosdado")
    l.append("Ana María Matute")
    l.append("Ana de Austria")
    l.append("Anacarsis")
    l.append("Anatole France")
    l.append("Anaxágoras")
    l.append("Andrew Bonar Law")
    l.append("André Breton")
    l.append("André Gide")
    l.append("André Giroux")
    l.append("André Malraux")
    l.append("André Massena")
    l.append("André Maurois")
    l.append("Anna Pavlova")
    l.append("Anne Robert Jacques Turgot")
    l.append("Anthelme Brillat-Savarín")
    l.append("Antoine Gombaud")
    l.append("Antoine Houdar de la Motte")
    l.append("Antoine de Saint-Exupery")
    l.append("Antoni Marí")
    l.append("Antoni Tapies")
    l.append("Antonie L. Apollinarie Fée")
    l.append("Antonio Cánovas del Castillo")
    l.append("Antonio Fraguas Forges")
    l.append("Antonio Francesco Doni")
    l.append("Antonio Gala")
    l.append("Antonio García Gutiérrez")
    l.append("Antonio Gaudí i Cornet")
    l.append("Antonio Genovesi")
    l.append("Antonio Machado")
    l.append("Antonio Marino Lemiere")
    l.append("Antonio Maura y Montaner")
    l.append("Antonio Mingote")
    l.append("Antonio Muñoz Molina")
    l.append("Antonio Porchia")
    l.append("Antón Pavlovich Chéjov")
    l.append("Anónimo")
    l.append("Aphra Behn")
    l.append("Aquiles Dalseme")
    l.append("Aristófanes")
    l.append("Aristóteles")
    l.append("Aristóteles Onassis")
    l.append("Armando Palacio Valdés")
    l.append("Arnold Bennett")
    l.append("Arnold H. Glasow")
    l.append("Arnold J. Toynbee")
    l.append("Arquímedes")
    l.append("Arthur C. Clarke")
    l.append("Arthur Helps")
    l.append("Arthur Koestler")
    l.append("Arthur Miller")
    l.append("Arthur Neville Chamberlain")
    l.append("Arthur Rimbaud")
    l.append("Arthur Schnitzler")
    l.append("Arthur Schopenhauer")
    l.append("Arturo Graf")
    l.append("Arturo Pérez Reverte")
    l.append("August von Kotzebue")
    l.append("Auguste Comte")
    l.append("Auguste Rodin")
    l.append("Aulo Persio")
    l.append("Aurelio Teodosio Macrobio")
    l.append("Averroes")
    l.append("Ayn Rand")
    l.append("Azorín")
    l.append("B. C. Forbes")
    l.append("B.B. King")
    l.append("Baldassare Castiglione")
    l.append("Baldomero Fernández Moreno")
    l.append("Balduino I")
    l.append("Baltasar Gracián")
    l.append("Barbara Probst Solomon")
    l.append("Barbara Ward")
    l.append("Baruch Benedict Spinoza")
    l.append("Barón de Holbach")
    l.append("Bella Abzug")
    l.append("Benedetto Croce")
    l.append("Benedicto XVI")
    l.append("Benito Jerónimo Feijoó")
    l.append("Benito Juárez")
    l.append("Benito Pérez Galdos")
    l.append("Benjamin Constant de Rebecque")
    l.append("Benjamin Disraeli")
    l.append("Benjamin Franklin")
    l.append("Benjamin Jonson")
    l.append("Benjamín Jarnés")
    l.append("Bernard Le Bouvier de Fontenelle")
    l.append("Bernard M. Baruch")
    l.append("Bernard-Henri Lévy")
    l.append("Bernardino Rebolledo")
    l.append("Bernardo Verbitsky")
    l.append("Bernice Buresh")
    l.append("Berthold Auerbach")
    l.append("Bertolt Brecht")
    l.append("Bertrand Russell")
    l.append("Bette Davis")
    l.append("Beverly Sills")
    l.append("Bias de Priene")
    l.append("Bill Cosby")
    l.append("Bill Watterson")
    l.append("Billy Wilder")
    l.append("Blaise Pascal")
    l.append("Blas Infante")
    l.append("Bob Dylan")
    l.append("Bob Marley")
    l.append("Boecio")
    l.append("Bono")
    l.append("Boris Leonídovich Pasternak")
    l.append("Brian Bowling")
    l.append("Bruce Springsteen")
    l.append("Buda")
    l.append("C. Spurgeon")
    l.append("C.C. Cortéz")
    l.append("Caballero de Bruix")
    l.append("Camille Sée")
    l.append("Camilo José Cela")
    l.append("Cardenal Richelieu")
    l.append("Cardenal de Retz")
    l.append("Carl August Sandburg")
    l.append("Carl Berstein")
    l.append("Carl Gustav Jung")
    l.append("Carl Maria von Weber")
    l.append("Carl Sagan")
    l.append("Carl Schmitt")
    l.append("Carl Zuckmayer")
    l.append("Carlo Bini")
    l.append("Carlo Dossi")
    l.append("Carlo Goldoni")
    l.append("Carlomagno")
    l.append("Carlos Castilla del Pino")
    l.append("Carlos Fuentes")
    l.append("Carlos I")
    l.append("Carmen Conde")
    l.append("Carmen Martín Gaite")
    l.append("Carmen Posadas")
    l.append("Casimir Delavigne")
    l.append("Catón de Útica")
    l.append("Cayo Cornelio Tácito")
    l.append("Cecilia")
    l.append("Cecilia Bohl de Faber")
    l.append("Cesare Beccaria")
    l.append("Cesare Cantù")
    l.append("Cesare Pavese")
    l.append("Chamfort")
    l.append("Channing Pollock")
    l.append("Charles  Kingsley")
    l.append("Charles Anderson Dana")
    l.append("Charles Augustin Sainte-Beuve")
    l.append("Charles Baudelaire")
    l.append("Charles Bukowski")
    l.append("Charles Caleb Colton")
    l.append("Charles Chaplin")
    l.append("Charles Dickens")
    l.append("Charles James Fox")
    l.append("Charles Lamb")
    l.append("Charles M. Schulz")
    l.append("Charles Nicolle")
    l.append("Charles Palissot de Montenoy")
    l.append("Charles Paul de Kock")
    l.append("Charles Pinot Duclós")
    l.append("Charles Péguy")
    l.append("Charles Reade")
    l.append("Charles Robert Darwin")
    l.append("Charles Régismanset")
    l.append("Charles Thomson Rees Wilson")
    l.append("Charles Van Lerberghe")
    l.append("Charles de Gaulle")
    l.append("Charles-Maurice Talleyrand Périgord")
    l.append("Charmesse")
    l.append("Chavela Vargas")
    l.append("Christoph A. Tiedge")
    l.append("Christoph Wieland")
    l.append("Christopher Morley")
    l.append("Chumy Chúmez")
    l.append("Ciro")
    l.append("Clarence S. Darrow")
    l.append("Claude Adrien Helvétius")
    l.append("Claude Bernard")
    l.append("Claude Chabrol")
    l.append("Claude Debussy")
    l.append("Claude Serre")
    l.append("Clemente XIV")
    l.append("Clemente XIX")
    l.append("Clemente de Alejandría")
    l.append("Cleóbulo de Lindos")
    l.append("Clifton Paul Fadiman")
    l.append("Clive Barker")
    l.append("Clive Staples Lewis")
    l.append("Coco Chanel")
    l.append("Colette")
    l.append("Colin Powell")
    l.append("Columela")
    l.append("Concepción Arenal")
    l.append("Conde de  Chesterfield")
    l.append("Conde de Mirabeau")
    l.append("Conde de Rivarol")
    l.append("Confucio")
    l.append("Constancio C. Vigil")
    l.append("Cristina II")
    l.append("Cristina Trivulzio di Belgioioso")
    l.append("Cristóbal Colón")
    l.append("Cruzalta")
    l.append("Curcio")
    l.append("Cyril Connolly")
    l.append("Cándido")
    l.append("César Borgia")
    l.append("César González-Ruano")
    l.append("César Vallejo")
    l.append("Dalai Lama")
    l.append("Dale Carnegie")
    l.append("Dame Daphne du Maurier")
    l.append("Dan Seligman")
    l.append("Daniel Defoe")
    l.append("Daniel Gélin")
    l.append("Dante Alighieri")
    l.append("Dario Fo")
    l.append("David  Lloyd George")
    l.append("David Brown")
    l.append("David Frost")
    l.append("David Herbert Lawrence")
    l.append("David Hockney")
    l.append("David Starr Jordan")
    l.append("David T. Kearns")
    l.append("David Viscott")
    l.append("Delphine-Gay de Girardin")
    l.append("Demetrio de Falero")
    l.append("Demonax")
    l.append("Demócrito de Abdera")
    l.append("Demóstenes")
    l.append("Deng Xiaoping")
    l.append("Denis Diderot")
    l.append("Denis de Rougemont")
    l.append("Diego Luís Córdoba")
    l.append("Diego de Saavedra Fajardo")
    l.append("Dionisio de Halicarnaso")
    l.append("Diógenes Laercio")
    l.append("Diógenes de Sínope")
    l.append("Dominique Pire")
    l.append("Doménico Cieri Estrada")
    l.append("Doris Lessing")
    l.append("Dorothy Parker")
    l.append("Doug Larson")
    l.append("Douglas Adams")
    l.append("Douglas Williams Jerrold")
    l.append("Duke Ellington")
    l.append("Duque de Levis")
    l.append("Duquesa de Abrantes")
    l.append("E. W. Stevens")
    l.append("E. de Geibel")
    l.append("E.T.A. Hoffmann")
    l.append("Earl Gray Stevens")
    l.append("Eckhart de Hochheim")
    l.append("Ed Cunningham")
    l.append("Eddy Cantor")
    l.append("Edgar Allan Poe")
    l.append("Edgar Degas")
    l.append("Edmond Gouncourt")
    l.append("Edmund Burke")
    l.append("Edmund Husserl")
    l.append("Edmund Wilson")
    l.append("Edmundo de Amicis")
    l.append("Eduard Thomas")
    l.append("Eduardo Chillida")
    l.append("Eduardo Galeano")
    l.append("Eduardo Mendoza")
    l.append("Edward Benjamin Britten")
    l.append("Edward George Bulwer-Lytton")
    l.append("Edward Kennedy")
    l.append("Edward Roscoe Murrow")
    l.append("El Talmud")
    l.append("Elbert Hubbard")
    l.append("Eleanor Roosevelt")
    l.append("Eliphas Lévi")
    l.append("Elizabeth Barrett Browing")
    l.append("Elizabeth Taylor")
    l.append("Elliot Gould")
    l.append("Elsa Triolet")
    l.append("Elías Canetti")
    l.append("Emil Ludwig")
    l.append("Emil Michel Cioran")
    l.append("Emile Verhaeren")
    l.append("Emilia Pardo Bazán")
    l.append("Emiliano Zapata")
    l.append("Emilio Alarcos Llorach")
    l.append("Emilio Castelar")
    l.append("Emilio Visconti Ventosa")
    l.append("Emily Dickinson")
    l.append("Emmanuel Joseph Sieyès")
    l.append("Enrique Ernesto  Febbraro")
    l.append("Enrique Jardiel Poncela")
    l.append("Enrique Miret Magdalena")
    l.append("Enrique Múgica Herzog")
    l.append("Enrique Tierno Galván")
    l.append("Ephraim Kishon")
    l.append("Epicteto de Frigia")
    l.append("Epicuro de Samos")
    l.append("Erasmo de Rotterdam")
    l.append("Eric Hoffer")
    l.append("Erich Fromm")
    l.append("Erich Kästner")
    l.append("Ernest Bersot")
    l.append("Ernest Hemingway")
    l.append("Ernest Thomas Sinton Walton")
    l.append("Ernesto 'Che' Guevara")
    l.append("Ernesto Cardenal")
    l.append("Ernesto Mallo")
    l.append("Ernesto Sábato")
    l.append("Ernst Wiechert")
    l.append("Erskine Caldwell")
    l.append("Esopo")
    l.append("Esquilo de Eleusis")
    l.append("Estrabón de Amasia")
    l.append("Ettore Scola")
    l.append("Eugene Ionesco")
    l.append("Eugene O'Neill")
    l.append("Eugeni d' Ors")
    l.append("Eugeni d'Ors")
    l.append("Eugenio Trias")
    l.append("Eugène Delacroix")
    l.append("Eurípides de Salamina")
    l.append("Eustache J. Langlois")
    l.append("Eustorgio Salgar")
    l.append("Evelyn Waugh")
    l.append("Everhardus Johannes Potgieter")
    l.append("Ezra Loomis Pound")
    l.append("F. A. Suárez")
    l.append("F. Heumer")
    l.append("F. William Robertson")
    l.append("Facundo Cabral")
    l.append("Federico Fellini")
    l.append("Federico García Lorca")
    l.append("Federico II")
    l.append("Federico Luis Jahn")
    l.append("Federico Mayor Zaragoza")
    l.append("Fedro")
    l.append("Felipe González Márquez")
    l.append("Ferdinand Brunetière")
    l.append("Ferdinand Galiani")
    l.append("Ferdinand Lassalle")
    l.append("Fernando Arrabal")
    l.append("Fernando Fernán Gomez")
    l.append("Fernando Pessoa")
    l.append("Fernando Savater")
    l.append("Fernando Sánchez Dragó")
    l.append("Fernando Trueba")
    l.append("Fernando de Rojas")
    l.append("Fidel Pintos")
    l.append("Fiodor Dostoievski")
    l.append("Flora Tristran")
    l.append("Focílides")
    l.append("Francesco Petrarca")
    l.append("Francis J. Braceland")
    l.append("Francis Picabia")
    l.append("Francis Scott Fitzgerald")
    l.append("Francis de Croisset")
    l.append("Francisco Ayala")
    l.append("Francisco Franco Bahamonde")
    l.append("Francisco Pi y Margall")
    l.append("Francisco Umbral")
    l.append("Francisco Villaespesa")
    l.append("Francisco de Goya")
    l.append("Francisco de Quevedo")
    l.append("Frank A. Clark")
    l.append("Frank Capra")
    l.append("Frank Lloyd Wright")
    l.append("Frank Sinatra")
    l.append("Frank Zappa")
    l.append("Franklin D. Roosevelt")
    l.append("Franklin P. Jones")
    l.append("Franz Grillparzer")
    l.append("Franz Kafka")
    l.append("Franz Liszt")
    l.append("Franz Schubert")
    l.append("Franz Werfel")
    l.append("François Mauriac")
    l.append("François Rabelais")
    l.append("François Truffaut")
    l.append("François de la Rochefoucauld")
    l.append("Françoise Giroud")
    l.append("Françoise Sagan")
    l.append("Fray Antonio de Guevara")
    l.append("Fray Luis de León")
    l.append("Fred Allen")
    l.append("Fred Hoyle")
    l.append("Frederic Burrhus Skinner")
    l.append("Friedrich Dürrenmatt")
    l.append("Friedrich Hebbel")
    l.append("Friedrich Nietzsche")
    l.append("Friedrich Schiller")
    l.append("Friedrich Weber")
    l.append("Friedrich von Logau")
    l.append("Fritz Eckhardt")
    l.append("Frédéric Chopin")
    l.append("Félecité de Lamennais")
    l.append("Félix María de Samaniego")
    l.append("Fénelon")
    l.append("G. Tohre")
    l.append("Gabriel Celaya")
    l.append("Gabriel García Márquez")
    l.append("Gabriel Marcel")
    l.append("Gabriela Mistral")
    l.append("Gabriele d' Annunzio")
    l.append("Galileo Galilei")
    l.append("Gar Mar")
    l.append("Garth Brooks")
    l.append("Gaspar Melchor de Jovellanos")
    l.append("Gasparo Gozzi")
    l.append("Gastón Bachelard")
    l.append("Georg Christoph Lichtenberg")
    l.append("Georg Simmel")
    l.append("Georg Wilhelm Friedrich Hegel")
    l.append("George Bernard Shaw")
    l.append("George Burns")
    l.append("George Calinescu")
    l.append("George Catlett Marshall")
    l.append("George Chapman")
    l.append("George Duby")
    l.append("George Eliot")
    l.append("George Gurdjieff")
    l.append("George Herbert")
    l.append("George Horace Lorimer")
    l.append("George Lucas")
    l.append("George Orwell")
    l.append("George S. Patton")
    l.append("George Sand")
    l.append("George Steiner")
    l.append("George Travelyan")
    l.append("George Villiers")
    l.append("George W. Lyttelton")
    l.append("George Washington")
    l.append("George William Curtis")
    l.append("Georges Benjamin Clemenceau")
    l.append("Georges Bidault")
    l.append("Georges Braque")
    l.append("Georges Courteline")
    l.append("Georges Duhamel")
    l.append("Georges Pompidou")
    l.append("Georges Poulet")
    l.append("Georges Simenon")
    l.append("Georgi Plejánov")
    l.append("Gerardo Diego")
    l.append("Germaine de Staël")
    l.append("Gertrude Stein")
    l.append("Giacomo Leopardi")
    l.append("Gilbert Cesbron")
    l.append("Gilbert Keith Chesterton")
    l.append("Giordano Bruno")
    l.append("Giovanni Boccaccio")
    l.append("Giovanni Guareschi")
    l.append("Giovanni Papini")
    l.append("Giulio Andreotti")
    l.append("Giuseppe Mazzini")
    l.append("Giuseppe Tomasi di Lampedusa")
    l.append("Godfrey H. Hardy")
    l.append("Gonzalo Santonja")
    l.append("Gonzalo Torrente Ballester")
    l.append("Gottfried Wilhelm Leibniz")
    l.append("Gotthold Ephraim Lessing")
    l.append("Graham Greene")
    l.append("Grant Morrison")
    l.append("Gregg Levoy")
    l.append("Gregorio Marañón")
    l.append("Groucho Marx")
    l.append("Guglielmo Ferrero")
    l.append("Guillermo Pérez Villalta")
    l.append("Gustave Flaubert")
    l.append("Gustavo Adolfo Bécquer")
    l.append("Gustavo Dorz")
    l.append("Gustavo Gutierrez Merino")
    l.append("Gustavo Le Bon")
    l.append("Guy Carcassonne")
    l.append("Guy de Maupassant")
    l.append("H. Greele")
    l.append("Habib Bourguiba")
    l.append("Hans Dietrich Genscher")
    l.append("Harold Bloom")
    l.append("Harold E. Edgerton")
    l.append("Harold MacMillan")
    l.append("Harold Pinter")
    l.append("Harold Wilson")
    l.append("Harriet Beecher Stowe")
    l.append("Harry Mulisch")
    l.append("Havey Keitel")
    l.append("Hector Berlioz")
    l.append("Heinrich  Böll")
    l.append("Heinrich Heine")
    l.append("Heinrich Wilhelm von Kleist")
    l.append("Heinz G. Konsalik")
    l.append("Helen Adams Keller")
    l.append("Helen Rowland")
    l.append("Helenio Herrera")
    l.append("Henri Barbusse")
    l.append("Henri Bergson")
    l.append("Henri Poincaré")
    l.append("Henrik Johan Ibsen")
    l.append("Henry Adams")
    l.append("Henry Bataille")
    l.append("Henry Brooks Adams")
    l.append("Henry David Thoreau")
    l.append("Henry F. Amiel")
    l.append("Henry F. Hoar")
    l.append("Henry Fielding")
    l.append("Henry Ford")
    l.append("Henry George")
    l.append("Henry Home Kames")
    l.append("Henry James")
    l.append("Henry John Kaiser")
    l.append("Henry Lewis Stimson")
    l.append("Henry Mackenzie")
    l.append("Henry Miller")
    l.append("Henry Moore")
    l.append("Henry Saint-John")
    l.append("Henry Van Dyke")
    l.append("Henry Wadsworth Longfellow")
    l.append("Henry Ward Beecher")
    l.append("Henry de Montherlant")
    l.append("Henry-Louis Mencken")
    l.append("Herbert George Wells")
    l.append("Herbert Marshall McLuhan")
    l.append("Herbert Spencer")
    l.append("Herbert Von Karajan")
    l.append("Herman Melville")
    l.append("Hermann Hesse")
    l.append("Hermann Keyserling")
    l.append("Herni Dominique Lacordaire")
    l.append("Hernán Cortés")
    l.append("Heráclito de Efeso")
    l.append("Heródoto de Halicarnaso")
    l.append("Hesíodo")
    l.append("Heywood Hale Broun")
    l.append("Hilda Owlsley")
    l.append("Hipócrates")
    l.append("Hipólito Taine")
    l.append("Hiram Warren Johnson")
    l.append("Hodding  Carter")
    l.append("Homero")
    l.append("Honoré de Balzac")
    l.append("Horace Mann")
    l.append("Horace Smith")
    l.append("Howard G. Hendricks")
    l.append("Hugo von Hofmannsthal")
    l.append("I. Heywood")
    l.append("Igor Stravinski")
    l.append("Immanuel Kant")
    l.append("Indira Gandhi")
    l.append("Ingmar Bergman")
    l.append("Ingrid Bergman")
    l.append("Ippolito Nievo")
    l.append("Isaac Asimov")
    l.append("Isaac Newton")
    l.append("Isabel Allende")
    l.append("Isabel de Rumania")
    l.append("Isadora Duncan")
    l.append("Isidoro Loi")
    l.append("Israel Zangwill")
    l.append("Isócrates")
    l.append("Italo Calvino")
    l.append("Ivan Turgueniev")
    l.append("J. Mario Simmel")
    l.append("J. Nievo")
    l.append("J. R. R. Tolkien")
    l.append("J.P. Sergent")
    l.append("Jacinto Benavente")
    l.append("Jacinto Octavio Picón")
    l.append("Jack Gould")
    l.append("Jacquelyn  Mitchard")
    l.append("Jacques Benigne Bossuet")
    l.append("Jacques Derrida")
    l.append("Jacques H. Bernardin de Saint Pierre")
    l.append("Jacques Prévert")
    l.append("Jacques Roumain")
    l.append("Jacques Yves Cousteau")
    l.append("Jacques de Lacretelle")
    l.append("Jaime Luciano Balmes")
    l.append("Jaime de Armiñán")
    l.append("James Baldwin")
    l.append("James Branch Cabell")
    l.append("James Carroll")
    l.append("James Cash Penny")
    l.append("James Cook")
    l.append("James Gibbons Huneker")
    l.append("James Joyce")
    l.append("James Russell Lowell")
    l.append("James Thurber")
    l.append("James William Fulbright")
    l.append("Jane Austen")
    l.append("Jane Fonda")
    l.append("Jaume Perich")
    l.append("Javier Sádaba")
    l.append("Jean Anouilh")
    l.append("Jean Baptiste Alphonse Karr")
    l.append("Jean Baptiste Say")
    l.append("Jean Cocteau")
    l.append("Jean Dubuffet")
    l.append("Jean Francois Revel")
    l.append("Jean Giono")
    l.append("Jean Jacques Rousseau")
    l.append("Jean Le Rond D' Alembert")
    l.append("Jean Luc Goddard")
    l.append("Jean Lucien Arréat")
    l.append("Jean Paul")
    l.append("Jean Paul Marat")
    l.append("Jean Paul Sartre")
    l.append("Jean Piaget")
    l.append("Jean Renoir")
    l.append("Jean Rostand")
    l.append("Jean de  Gerson")
    l.append("Jean de La Fontaine")
    l.append("Jean de Monet")
    l.append("Jean de la Bruyere")
    l.append("Jean-Baptiste Racine")
    l.append("Jean-Louis Barrault")
    l.append("Jeannette Rankin")
    l.append("Jehudi Menuhin")
    l.append("Jerome Klapka Jerome")
    l.append("Jerry Lewis")
    l.append("Jesucristo")
    l.append("Jesús Fernández Santos")
    l.append("Jesús Hermida")
    l.append("Jim Backus")
    l.append("Jim Fox")
    l.append("Joan Baez")
    l.append("Joan Manuel Serrat")
    l.append("Joaquín Bartrina")
    l.append("Joaquín Oristrell")
    l.append("Joaquín Sabina")
    l.append("Johann August Strindberg")
    l.append("Johann Gütemberg")
    l.append("Johann Herder")
    l.append("Johann J. Engel")
    l.append("Johann Kaspar Lavater")
    l.append("Johann Wolfgang Goethe")
    l.append("Johannes Brahms")
    l.append("Johh Hessin Clarke")
    l.append("John Archibald")
    l.append("John Ashbery")
    l.append("John Baines")
    l.append("John Boyle O'Reilly")
    l.append("John Cage")
    l.append("John Calvin Coolidge")
    l.append("John Churton Collins")
    l.append("John Cleese")
    l.append("John D. Rockefeller")
    l.append("John Dewey")
    l.append("John Donne")
    l.append("John Dos Passos")
    l.append("John Dryden")
    l.append("John Ernst Steinbeck")
    l.append("John Fitzgerald Kennedy")
    l.append("John Fletcher")
    l.append("John Galsworthy")
    l.append("John Gay")
    l.append("John H. Newman")
    l.append("John Irving")
    l.append("John Keats")
    l.append("John Kenneth Galbraith")
    l.append("John Lennon")
    l.append("John Locke")
    l.append("John Maynard Keynes")
    l.append("John Milton")
    l.append("John Ray")
    l.append("John Ruskin")
    l.append("John Stuart Mill")
    l.append("John Wesley")
    l.append("John Wilmot")
    l.append("Jonas Edward Salk")
    l.append("Jonathan Swift")
    l.append("Jordi Sabater Pi")
    l.append("Jorge Boccanera")
    l.append("Jorge Bucay")
    l.append("Jorge Guillén")
    l.append("Jorge Luis Borges")
    l.append("Jorge Santayana")
    l.append("Jose Luis de Villalonga")
    l.append("Jose María de Pereda")
    l.append("Josep Pla")
    l.append("Joseph Addison")
    l.append("Joseph Conrad")
    l.append("Joseph Ernest Renan")
    l.append("Joseph Fouché")
    l.append("Joseph Heller")
    l.append("Joseph Joubert")
    l.append("Joseph Roux")
    l.append("Joseph Sanial-Dubay")
    l.append("Josh Billings")
    l.append("Jostein Gaarder")
    l.append("José Antonio Marina")
    l.append("José Bergamín")
    l.append("José Gorostiza")
    l.append("José Hernández")
    l.append("José Hierro")
    l.append("José Ingenieros")
    l.append("José Luis Coll")
    l.append("José Luis Sampedro")
    l.append("José Luís López Aranguren")
    l.append("José Martí")
    l.append("José María Eça de Queirós")
    l.append("José María Pemán")
    l.append("José María Rodero")
    l.append("José María Vargas Vila")
    l.append("José Miguel Monzón")
    l.append("José Narosky")
    l.append("José O. Caldas")
    l.append("José Ortega y Gasset")
    l.append("José Saramago")
    l.append("José Vasconcelos")
    l.append("José de Espronceda")
    l.append("José de San Martín")
    l.append("Juan Carlos Onetti")
    l.append("Juan Donoso Cortés")
    l.append("Juan Eusebio Nieremberg")
    l.append("Juan Gris")
    l.append("Juan Luis Vives")
    l.append("Juan Pablo II")
    l.append("Juan Ramón Jiménez")
    l.append("Juan Rulfo")
    l.append("Juan Teba")
    l.append("Juan Valera")
    l.append("Juan XXIII")
    l.append("Juan Zorrilla de San Martín")
    l.append("Juana de Ibarbourou")
    l.append("Judy Grahn")
    l.append("Jules  Sandeau")
    l.append("Jules Amédée Barbey d'Aurevilly")
    l.append("Jules Gouncourt")
    l.append("Jules Michelet")
    l.append("Jules Renard")
    l.append("Jules de Gaultier")
    l.append("Julia Ward Howe")
    l.append("Julian Green")
    l.append("Julie de Lespinasse")
    l.append("Julio Anguita")
    l.append("Julio Cerón")
    l.append("Julio Cortázar")
    l.append("Julio César")
    l.append("Julio Verne")
    l.append("Julius Robert  Oppenheimer")
    l.append("Julián Marías")
    l.append("Juvenal")
    l.append("Kalidasa")
    l.append("Karl A. Menninger")
    l.append("Karl Barth")
    l.append("Karl Kraus")
    l.append("Karl Marx")
    l.append("Karl Raimund Popper")
    l.append("Karl Theodor Jaspers")
    l.append("Karl Wilhelm Von Humboldt")
    l.append("Karlheinz Stockhausen")
    l.append("Katharine Hepburn")
    l.append("Katherine Mansfield")
    l.append("Kazimierz Brandys")
    l.append("Ken Robinson")
    l.append("Khalil Gibran")
    l.append("Kin Hubbard")
    l.append("Kirk Douglas")
    l.append("Knut Hamsum")
    l.append("Kofi Annan")
    l.append("Konrad Adenauer")
    l.append("Konstantín Eduardovich Tsiolkovski")
    l.append("Kurt D. Cobain")
    l.append("Kurt Tucholsky")
    l.append("L. Peter")
    l.append("Lajos Kossuth")
    l.append("Lana Turner")
    l.append("Lao-tsé")
    l.append("Laura Morante")
    l.append("Laure Conan")
    l.append("Laurence Johnston Peter")
    l.append("Laurence Sterne")
    l.append("Le Thangh Tonh")
    l.append("Lee Smolin")
    l.append("Len Wein")
    l.append("Leon Battista Alberti")
    l.append("Leon Tolstoi")
    l.append("Leonard Bernstein")
    l.append("Leonard Cohen")
    l.append("Leonardo Da Vinci")
    l.append("Leonid Andréiev")
    l.append("Lewis Carroll")
    l.append("León  Trotski")
    l.append("León Bloy")
    l.append("León Daudet")
    l.append("León Daudí")
    l.append("León Felipe")
    l.append("León Gieco")
    l.append("Li Tai-Po")
    l.append("Lilliam Hellman")
    l.append("Lin Yutang")
    l.append("Lindsay Kemp")
    l.append("Lingrée")
    l.append("Llorenç Villalonga")
    l.append("Lope de Vega")
    l.append("Lord Acton")
    l.append("Lord Brougham")
    l.append("Lord Byron")
    l.append("Louis Bourdaloue")
    l.append("Louis Charles Alfred de Musset")
    l.append("Louis Dumur")
    l.append("Louis Emmanuel Dupaty")
    l.append("Louis Lavelle")
    l.append("Louis McHenry Howe")
    l.append("Louis Pasteur")
    l.append("Louis de Bonald")
    l.append("Louis de Jaucourt")
    l.append("Louis de Saint-Just")
    l.append("Louis-Antoine Caraccioli")
    l.append("Louise May Alcott")
    l.append("Lu Xun")
    l.append("Luchino Visconti")
    l.append("Luciano Pavarotti")
    l.append("Lucio Anneo Séneca")
    l.append("Lucio Apuleyo")
    l.append("Lucrecio")
    l.append("Lucía Extebarria")
    l.append("Ludwig Börne")
    l.append("Ludwig Feuerbach")
    l.append("Ludwig Wittgenstein")
    l.append("Ludwig van Beethoven")
    l.append("Luis Buñuel")
    l.append("Luis Cernuda")
    l.append("Luis Coloma")
    l.append("Luis García Berlanga")
    l.append("Luis Herrero")
    l.append("Luis Rojas Marcos")
    l.append("Luis XIV de Francia")
    l.append("Luis XV de Francia")
    l.append("Luis de Góngora y Argote")
    l.append("M. Brickman")
    l.append("M. J. Smith")
    l.append("Madame Basta")
    l.append("Madame Roland")
    l.append("Madeleine de Scudéry")
    l.append("Madre Teresa de Calcuta")
    l.append("Mae West")
    l.append("Magdalena Martínez")
    l.append("Mahatma Gandhi")
    l.append("Malesherbes")
    l.append("Manuel  Gayol Fernández")
    l.append("Manuel Azaña")
    l.append("Manuel Campo Vidal")
    l.append("Manuel Castells")
    l.append("Manuel Vicent")
    l.append("Mao Tse-Tung")
    l.append("Marc Chagall")
    l.append("Marcel Aymé")
    l.append("Marcel Duchamp")
    l.append("Marcel Jouhandeau")
    l.append("Marcel Mart")
    l.append("Marcel Pagnol")
    l.append("Marcel Proust")
    l.append("Marcel Prévost")
    l.append("Marcelino Camacho")
    l.append("Marco Anneo Lucano")
    l.append("Marco Aurelio")
    l.append("Marco Aurelio Almazán")
    l.append("Marco Tulio Cicerón")
    l.append("Marco Valerio Marcial")
    l.append("Marcus Fabis Quintiliano")
    l.append("Margaret Mitchel")
    l.append("Margaret Oliphant Oliphant")
    l.append("Margaret Thatcher")
    l.append("Marguerite Duras")
    l.append("Marguerite Yourcenar")
    l.append("Maria Montessori")
    l.append("Mariano Aguiló")
    l.append("Mariano José de Larra")
    l.append("Marie Curie")
    l.append("Marie von Ebner-Eschenbach")
    l.append("Marilyn Monroe")
    l.append("Mario Benedetti")
    l.append("Mario Moreno 'Cantinflas'")
    l.append("Mario Puzo")
    l.append("Mario Vargas Llosa")
    l.append("Mark Twain")
    l.append("Marlene Dietrich")
    l.append("Marquesa de Maintenon")
    l.append("Marquesa de Sévigné")
    l.append("Marqués de La Fayette")
    l.append("Marqués de Sade")
    l.append("Marqués de Vauvenargues")
    l.append("Marta Mason")
    l.append("Martin Heidegger")
    l.append("Martin Lutero")
    l.append("Martin Luther King")
    l.append("Martin Niemoeller")
    l.append("Maruja Torres")
    l.append("Mary Tyler Moore")
    l.append("María Teresa I de Austria")
    l.append("Mateo Alemán")
    l.append("Maurice Maeterlinck")
    l.append("Maurice Saatchi")
    l.append("Max Ernst")
    l.append("Max Frisch")
    l.append("Max Jacobs")
    l.append("Max Planck")
    l.append("Maximilian Robespierre")
    l.append("Mayer Amschel Rothschild")
    l.append("Menandro de Atenas")
    l.append("Mencio")
    l.append("Mercedes Milá")
    l.append("Michael Jordan")
    l.append("Michael Levine")
    l.append("Michael Medved")
    l.append("Michel Eyquem de Montaigne")
    l.append("Michel Foucault")
    l.append("Michelangelo Antonioni")
    l.append("Mignon McLaughlin")
    l.append("Miguel Delibes")
    l.append("Miguel Servet")
    l.append("Miguel de Cervantes Saavedra")
    l.append("Miguel de Unamuno")
    l.append("Mijail Bakunin")
    l.append("Mika Waltari")
    l.append("Milan Kundera")
    l.append("Miles Davis")
    l.append("Miquel Martí i Pol")
    l.append("Molière")
    l.append("Montesquieu")
    l.append("Montserrat Caballé")
    l.append("Moritz Gottlieb Saphir")
    l.append("Morris West")
    l.append("Moshe Dayan")
    l.append("Muslih-Ud-Din Saadi")
    l.append("Máximo Gorki")
    l.append("Nadine Gordimer")
    l.append("Naguib Mahfuz")
    l.append("Napoleón I")
    l.append("Newton Norman Minow")
    l.append("Nicolai Hartmann")
    l.append("Nicolas Boileau")
    l.append("Nicolas Malebranche")
    l.append("Nicolás Maquiavelo")
    l.append("Nicolás Tommaseo")
    l.append("Nicolás de Avellaneda")
    l.append("Nikita Jruschov")
    l.append("Nikita Jrushchov")
    l.append("Nikola Tesla")
    l.append("Nils Kjaer")
    l.append("Ninon de Lenclos")
    l.append("Noam Chomsky")
    l.append("Noel Clarasó")
    l.append("Noel Coward")
    l.append("Nora Ephron")
    l.append("Norbert Wiener")
    l.append("Norm Coleman")
    l.append("Norman Birkett")
    l.append("Norman Maclean")
    l.append("Norman Mailer")
    l.append("Norman Vincent Peale")
    l.append("Novalis")
    l.append("Numa Pompilio")
    l.append("Nuria Barrios")
    l.append("Nuria Espert")
    l.append("O. K. Bernhardt")
    l.append("Octavio Paz")
    l.append("Ogden Nash")
    l.append("Oleg Efremov")
    l.append("Olga Orozco")
    l.append("Oliver Goldsmith")
    l.append("Oliver Wendell Holmes")
    l.append("Oliverio Girondo")
    l.append("Omar Khayyam")
    l.append("Oriol Bohigas")
    l.append("Orison Swett Marden")
    l.append("Orson Welles")
    l.append("Oscar Wilde")
    l.append("Osvaldo Terranova")
    l.append("Otto Wagner")
    l.append("Otto von Bismark")
    l.append("Ovidio")
    l.append("Pablo Neruda")
    l.append("Pablo Picasso")
    l.append("Pablo VI")
    l.append("Paolo Mantegazza")
    l.append("Paracelso")
    l.append("Patrick J. Kennedy")
    l.append("Paul Auguez")
    l.append("Paul Auster")
    l.append("Paul Bowles")
    l.append("Paul Brulat")
    l.append("Paul Charles Bourget")
    l.append("Paul Claudel")
    l.append("Paul Géraldy")
    l.append("Paul Jean Toulet")
    l.append("Paul Joseph Goebbels")
    l.append("Paul Masson")
    l.append("Paul Morand")
    l.append("Paul Samuelson")
    l.append("Paul Valéry")
    l.append("Paul Verhoeven")
    l.append("Paul Verlaine")
    l.append("Paulo Coelho")
    l.append("Pearl S. Buck")
    l.append("Pedro Almodovar")
    l.append("Pedro Calderón de la Barca")
    l.append("Pedro Laín Entralgo")
    l.append("Pedro Muñoz Seca")
    l.append("Pedro Ruiz")
    l.append("Percy Bysshe Shelley")
    l.append("Peter Alexander Ustinov")
    l.append("Peter Drucker")
    l.append("Peter de Vries")
    l.append("Peña y Goñi")
    l.append("Philip Gibbs")
    l.append("Phillips Brooks")
    l.append("Pier Paolo Pasolini")
    l.append("Pierre Auguste Renoir")
    l.append("Pierre Augustin de Beaumarchais")
    l.append("Pierre Benoit")
    l.append("Pierre Bonnard")
    l.append("Pierre Corneille")
    l.append("Pierre Eugèn Marcellin Berthelot")
    l.append("Pierre Joseph Proudhon")
    l.append("Pierre Teilhard de Chardin")
    l.append("Pietro Colletta")
    l.append("Pietro Metastasio")
    l.append("Pilar Avivar")
    l.append("Piotr Ilich Tchaikovski")
    l.append("Pitaco de Mitilene")
    l.append("Pitigrilli")
    l.append("Pitágoras de Samos")
    l.append("Platón")
    l.append("Plauto")
    l.append("Plinio el Joven")
    l.append("Plinio el Viejo")
    l.append("Plutarco")
    l.append("Prosper Mérimée")
    l.append("Proverbio")
    l.append("Proverbio africano")
    l.append("Proverbio alemán")
    l.append("Proverbio americano")
    l.append("Proverbio armenio")
    l.append("Proverbio chino")
    l.append("Proverbio danés")
    l.append("Proverbio egipcio")
    l.append("Proverbio escocés")
    l.append("Proverbio estoniano")
    l.append("Proverbio galés")
    l.append("Proverbio ganés")
    l.append("Proverbio griego")
    l.append("Proverbio hebreo")
    l.append("Proverbio hindú")
    l.append("Proverbio holandés")
    l.append("Proverbio húngaro")
    l.append("Proverbio indio")
    l.append("Proverbio inglés")
    l.append("Proverbio irlandés")
    l.append("Proverbio italiano")
    l.append("Proverbio japonés")
    l.append("Proverbio judío")
    l.append("Proverbio latino")
    l.append("Proverbio manchú")
    l.append("Proverbio mexicano")
    l.append("Proverbio oriental")
    l.append("Proverbio persa")
    l.append("Proverbio polaco")
    l.append("Proverbio portugués")
    l.append("Proverbio rumano")
    l.append("Proverbio ruso")
    l.append("Proverbio sueco")
    l.append("Proverbio suizo")
    l.append("Proverbio turco")
    l.append("Proverbio yugoslavo")
    l.append("Proverbio árabe")
    l.append("Príncipe Carlos José de Ligne")
    l.append("Publio Siro")
    l.append("Publio Terencio Afer")
    l.append("Píndaro")
    l.append("Pío Baroja")
    l.append("Quino")
    l.append("Quinto Ennio")
    l.append("Quinto Horacio Flaco")
    l.append("Rabindranath Tagore")
    l.append("Rafael Alberti")
    l.append("Rafael Gibelli")
    l.append("Rainer María Rilke")
    l.append("Ralph Bunche")
    l.append("Ralph Nader")
    l.append("Ralph Waldo Emerson")
    l.append("Ramiro de Maeztu")
    l.append("Ramón Buenaventura")
    l.append("Ramón Gómez de la Serna")
    l.append("Ramón J. Sénder")
    l.append("Ramón Llull")
    l.append("Ramón María del Valle-Inclán")
    l.append("Ramón Pérez de Ayala")
    l.append("Ramón de Campoamor")
    l.append("Randolph")
    l.append("Raul Soldi")
    l.append("Raymond Chandler")
    l.append("Raymond Poincaré")
    l.append("Refrán")
    l.append("Remy de Gourmont")
    l.append("René Descartes")
    l.append("René Schenker")
    l.append("René de Chateaubriand")
    l.append("Reveillere")
    l.append("Ricardo Güiraldes")
    l.append("Richard Bach")
    l.append("Richard Kingston")
    l.append("Richard Moss")
    l.append("Richard Steele")
    l.append("Richard Whately")
    l.append("Rob Goldston")
    l.append("Robert Anderson")
    l.append("Robert Baden-Powell")
    l.append("Robert Bolt")
    l.append("Robert Browning")
    l.append("Robert Burns")
    l.append("Robert Burton")
    l.append("Robert Green Ingersoll")
    l.append("Robert Kennedy")
    l.append("Robert Koch")
    l.append("Robert Lee Frost")
    l.append("Robert Lemke")
    l.append("Robert Louis Stevenson")
    l.append("Robert Penn Warren")
    l.append("Robert Schumann")
    l.append("Robert Spaemann")
    l.append("Roberto Fontanarrosa")
    l.append("Roberto Sapriza")
    l.append("Rodríguez Marín")
    l.append("Roger Martin du Gard")
    l.append("Roger Wolfe")
    l.append("Romain Rolland")
    l.append("Romy Schneider")
    l.append("Ronald Reagan")
    l.append("Rosa Chacel")
    l.append("Rosa Montero")
    l.append("Rosa Regàs")
    l.append("Rubén Darío")
    l.append("Rudolf Virchow")
    l.append("Rudyard Kipling")
    l.append("S. Chase")
    l.append("S. Harris")
    l.append("S. Kent")
    l.append("S. Siporin")
    l.append("Sacha Guitry")
    l.append("Salman Rushdie")
    l.append("Salomón")
    l.append("Salustio")
    l.append("Salvador Dalí")
    l.append("Sam Keen")
    l.append("Samuel Alexander")
    l.append("Samuel Beckett")
    l.append("Samuel Butler (novelista)")
    l.append("Samuel Goldwyn")
    l.append("Samuel Johnson")
    l.append("Samuel Smiles")
    l.append("Samuel Taylor Coleridge")
    l.append("San Agustín")
    l.append("San Bernardo de Claraval")
    l.append("San Francisco de Sales")
    l.append("San Jerónimo")
    l.append("San Juan")
    l.append("San Mateo")
    l.append("San Pablo")
    l.append("Santa Catalina de Siena")
    l.append("Santa Teresa de Jesús")
    l.append("Santiago Carrillo")
    l.append("Santiago Ramón y Cajal")
    l.append("Santiago Rusiñol i Prats")
    l.append("Santo Tomás de Aquino")
    l.append("Santos López Pelegrín 'Abenamar'")
    l.append("Sealtiel Alatriste")
    l.append("Selma Lagerlof")
    l.append("Severo Catalina")
    l.append("Severo Ochoa")
    l.append("Shirley MacLaine")
    l.append("Sidney Lumet")
    l.append("Sigmund Freud")
    l.append("Silvio Pellico")
    l.append("Simone Weil")
    l.append("Simone de Beauvoir")
    l.append("Simón Bolívar")
    l.append("Sir Arthur Conan Doyle")
    l.append("Sir Francis Bacon")
    l.append("Sir Hugh Seymour Walpole")
    l.append("Sir John Bowring")
    l.append("Sir Laurence Olivier")
    l.append("Sofocleto")
    l.append("Solón de Atenas")
    l.append("Sorcha Carey")
    l.append("Sorell")
    l.append("Sri Pandit Jawaharlal Nehru")
    l.append("Stanislas de Boufflers")
    l.append("Stanislaw Jerzy Lec")
    l.append("Stanislaw Lem")
    l.append("Stanley Kubrick")
    l.append("Stefan Zweig")
    l.append("Stendhal")
    l.append("Stephen Leacock")
    l.append("Steve Jobs")
    l.append("Steven Brust")
    l.append("Suetonio")
    l.append("Sun Tzu")
    l.append("Susan Sontag")
    l.append("Susanna Tamaro")
    l.append("Svetlana Stalin")
    l.append("Swami Sivananda")
    l.append("Swami Vivekananda")
    l.append("Sándor Márai")
    l.append("Sócrates")
    l.append("Sófocles")
    l.append("Sören Aabye Kierkegaard")
    l.append("T. Reik")
    l.append("Tales de Mileto")
    l.append("Tayeb Saleh")
    l.append("Tennessee Williams")
    l.append("Theidir Ninnseb")
    l.append("Theodor W. Adorno")
    l.append("Theodore Hesburgh")
    l.append("Theodore Roosevelt")
    l.append("Theophilus Presbyter")
    l.append("Thiessen")
    l.append("Thomas Alva Edison")
    l.append("Thomas Browne")
    l.append("Thomas C. Wolfe")
    l.append("Thomas Carlyle")
    l.append("Thomas Chalmers")
    l.append("Thomas Corneille")
    l.append("Thomas De Kempis")
    l.append("Thomas De Quincey")
    l.append("Thomas Fuller")
    l.append("Thomas Henry Huxley")
    l.append("Thomas Hobbes")
    l.append("Thomas Jefferson")
    l.append("Thomas Louis Berger")
    l.append("Thomas Macaulay")
    l.append("Thomas Mann")
    l.append("Thomas Middleton")
    l.append("Thomas Moore")
    l.append("Thomas Paine")
    l.append("Thomas Shadwell")
    l.append("Thomas Stearns Eliot")
    l.append("Thomas Wentworth Higginson")
    l.append("Thomas Woodrow Wilson")
    l.append("Thornton Niven Wilder")
    l.append("Théodule-Armand Ribot")
    l.append("Théophile Gautier")
    l.append("Tiberio")
    l.append("Tirso de  Molina")
    l.append("Tito Livio")
    l.append("Tom Stoppard")
    l.append("Tristan Bernard")
    l.append("Truman Capote")
    l.append("Trygve Halvdan Lie")
    l.append("Tucídides")
    l.append("Tácito")
    l.append("Ugo Foscolo")
    l.append("Ulpiano")
    l.append("Umberto Eco")
    l.append("Upton Sinclair")
    l.append("Valeriu Butulescu")
    l.append("Vanessa Redgrave")
    l.append("Vegecio")
    l.append("Vicente Blasco Ibáñez")
    l.append("Vicente Espinel")
    l.append("Vicki Baum")
    l.append("Victor Hugo")
    l.append("Victor Montenegro")
    l.append("Victor Pauchet")
    l.append("Victoria Camps")
    l.append("Viktor Frankl")
    l.append("Vincent Van Gogh")
    l.append("Vincent Voiture")
    l.append("Vincenzo Gioberti")
    l.append("Violeta Chamorro")
    l.append("Virgilio")
    l.append("Virginia Vilanova")
    l.append("Vittorio Alfieri")
    l.append("Vittorio Gassman")
    l.append("Vittorio de Sica")
    l.append("Vizconde de Ponson du Terrail")
    l.append("Vladimir Nabokov")
    l.append("Voltaire")
    l.append("Václav Havel")
    l.append("Víctor Manuel")
    l.append("Víctor Ruiz Iriarte")
    l.append("W. C. Fields")
    l.append("Wallace Stevens")
    l.append("Walt Whitman")
    l.append("Walter Bagehot")
    l.append("Walter C. Sellar")
    l.append("Walter Lippmann")
    l.append("Walter Scott")
    l.append("Wayne W. Dyer")
    l.append("Wenceslao Fernández Florez")
    l.append("Werner Karl Heisenberg")
    l.append("Wernher Von Braun")
    l.append("Will Durant")
    l.append("Will Rogers")
    l.append("Willem de Kooning")
    l.append("William Blake")
    l.append("William Camden")
    l.append("William Cowper")
    l.append("William Ernest Henley")
    l.append("William Faulkner")
    l.append("William George Ward")
    l.append("William Godwin")
    l.append("William Hazlitt")
    l.append("William Hill")
    l.append("William James")
    l.append("William M. Bulger")
    l.append("William Penn")
    l.append("William Ross Wallace")
    l.append("William Rotsler")
    l.append("William Shakespeare")
    l.append("William Shankly")
    l.append("William Somerset Maugham")
    l.append("William Wordsworth")
    l.append("Willy Brandt")
    l.append("Winston Churchill")
    l.append("Wolfgang Amadeus Mozart")
    l.append("Woody Allen")
    l.append("Wystan Hugh Auden")
    l.append("Yeoryos Seferis")
    l.append("Yevgeny Yevtushenko")
    l.append("Yuel-Ji")
    l.append("Yvon Bunin")
    l.append("Zsa Zsa Gabor")
    l.append("Álvaro de Figueroa y Torres")
    l.append("Ángel Ganivet")
    l.append("Ángel Gonzalez")
    l.append("Édouard René Lefebvre de  Laboulaye")
    l.append("Émile Boutroux")
    l.append("Émile Zola")
    l.append("Étienne Bonnot de Condillac")
    l.append("Óscar Pin")
    l.append("Abraham Lincoln")
    l.append("Alain")
    l.append("Albert Camus")
    l.append("Albert Einstein")
    l.append("Aldous Huxley")
    l.append("Alejandro Casona")
    l.append("Alejandro Dumas")
    l.append("Alexander Pope")
    l.append("Alphonse de Lamartine")
    l.append("Amado Nervo")
    l.append("Ambrose Bierce")
    l.append("Anatole France")
    l.append("André Gide")
    l.append("André Maurois")
    l.append("Antoine de Saint-Exupery")
    l.append("Antonio Gala")
    l.append("Antonio Machado")
    l.append("Anónimo")
    l.append("Aristóteles")
    l.append("Arthur Miller")
    l.append("Arthur Schopenhauer")
    l.append("Arturo Graf")
    l.append("Baltasar Gracián")
    l.append("Benjamin Disraeli")
    l.append("Benjamin Franklin")
    l.append("Bertrand Russell")
    l.append("Blaise Pascal")
    l.append("Buda")
    l.append("Camilo José Cela")
    l.append("Carlos Fuentes")
    l.append("Chamfort")
    l.append("Charles Baudelaire")
    l.append("Charles Dickens")
    l.append("Clive Staples Lewis")
    l.append("Concepción Arenal")
    l.append("Confucio")
    l.append("Dante Alighieri")
    l.append("Denis Diderot")
    l.append("Edgar Allan Poe")
    l.append("Edmund Burke")
    l.append("Elbert Hubbard")
    l.append("Enrique Jardiel Poncela")
    l.append("Epicteto de Frigia")
    l.append("Epicuro de Samos")
    l.append("Erasmo de Rotterdam")
    l.append("Ernest Hemingway")
    l.append("Ernesto Sábato")
    l.append("Fiodor Dostoievski")
    l.append("Francisco de Quevedo")
    l.append("François Mauriac")
    l.append("François de la Rochefoucauld")
    l.append("Friedrich Hebbel")
    l.append("Friedrich Nietzsche")
    l.append("Friedrich Schiller")
    l.append("Fénelon")
    l.append("Gabriel García Márquez")
    l.append("Georg Christoph Lichtenberg")
    l.append("Georg Simmel")
    l.append("George Bernard Shaw")
    l.append("George Eliot")
    l.append("George Herbert")
    l.append("George Sand")
    l.append("Georges Benjamin Clemenceau")
    l.append("Germaine de Staël")
    l.append("Giacomo Leopardi")
    l.append("Gilbert Keith Chesterton")
    l.append("Giovanni Papini")
    l.append("Graham Greene")
    l.append("Gregorio Marañón")
    l.append("Groucho Marx")
    l.append("Gustave Flaubert")
    l.append("Gustavo Adolfo Bécquer")
    l.append("Gustavo Le Bon")
    l.append("Heinrich Heine")
    l.append("Henrik Johan Ibsen")
    l.append("Henry David Thoreau")
    l.append("Henry F. Amiel")
    l.append("Henry Ford")
    l.append("Henry-Louis Mencken")
    l.append("Hermann Hesse")
    l.append("Heráclito de Efeso")
    l.append("Hesíodo")
    l.append("Homero")
    l.append("Honoré de Balzac")
    l.append("Immanuel Kant")
    l.append("Jacinto Benavente")
    l.append("Jacques Benigne Bossuet")
    l.append("Jaime Luciano Balmes")
    l.append("Jaume Perich")
    l.append("Jean Baptiste Alphonse Karr")
    l.append("Jean Cocteau")
    l.append("Jean Jacques Rousseau")
    l.append("Jean Paul Sartre")
    l.append("Jean de La Fontaine")
    l.append("Jean de la Bruyere")
    l.append("Johann Wolfgang Goethe")
    l.append("John Fitzgerald Kennedy")
    l.append("John Ruskin")
    l.append("John Stuart Mill")
    l.append("Jonathan Swift")
    l.append("Jorge Luis Borges")
    l.append("Joseph Joubert")
    l.append("José Ingenieros")
    l.append("José Martí")
    l.append("José Ortega y Gasset")
    l.append("José Saramago")
    l.append("Juan Luis Vives")
    l.append("Juan Pablo II")
    l.append("Jules Renard")
    l.append("Juvenal")
    l.append("Karl Marx")
    l.append("Khalil Gibran")
    l.append("Lao-tsé")
    l.append("Leon Tolstoi")
    l.append("Leonardo Da Vinci")
    l.append("Lope de Vega")
    l.append("Lord Byron")
    l.append("Louis Charles Alfred de Musset")
    l.append("Lucio Anneo Séneca")
    l.append("Madre Teresa de Calcuta")
    l.append("Mahatma Gandhi")
    l.append("Marcel Proust")
    l.append("Marco Tulio Cicerón")
    l.append("Mariano José de Larra")
    l.append("Mario Benedetti")
    l.append("Mark Twain")
    l.append("Martin Luther King")
    l.append("Maurice Maeterlinck")
    l.append("Michel Eyquem de Montaigne")
    l.append("Miguel de Cervantes Saavedra")
    l.append("Miguel de Unamuno")
    l.append("Molière")
    l.append("Montesquieu")
    l.append("Napoleón I")
    l.append("Nicolas Boileau")
    l.append("Nicolás Maquiavelo")
    l.append("Noel Clarasó")
    l.append("Novalis")
    l.append("Octavio Paz")
    l.append("Oliver Wendell Holmes")
    l.append("Oscar Wilde")
    l.append("Otto von Bismark")
    l.append("Ovidio")
    l.append("Pablo Neruda")
    l.append("Pablo Picasso")
    l.append("Paul Valéry")
    l.append("Paulo Coelho")
    l.append("Pedro Calderón de la Barca")
    l.append("Pierre Corneille")
    l.append("Pitágoras de Samos")
    l.append("Platón")
    l.append("Plutarco")
    l.append("Proverbio chino")
    l.append("Proverbio árabe")
    l.append("Publio Siro")
    l.append("Pío Baroja")
    l.append("Quinto Horacio Flaco")
    l.append("Rabindranath Tagore")
    l.append("Ralph Waldo Emerson")
    l.append("Ramón Gómez de la Serna")
    l.append("Ramón de Campoamor")
    l.append("Refrán")
    l.append("René Descartes")
    l.append("René de Chateaubriand")
    l.append("Robert Lee Frost")
    l.append("Robert Louis Stevenson")
    l.append("Sacha Guitry")
    l.append("Samuel Johnson")
    l.append("San Agustín")
    l.append("Santa Teresa de Jesús")
    l.append("Santiago Ramón y Cajal")
    l.append("Santo Tomás de Aquino")
    l.append("Sigmund Freud")
    l.append("Simone de Beauvoir")
    l.append("Simón Bolívar")
    l.append("Sir Francis Bacon")
    l.append("Stanislaw Jerzy Lec")
    l.append("Stendhal")
    l.append("Sócrates")
    l.append("Sófocles")
    l.append("Thomas Carlyle")
    l.append("Thomas Fuller")
    l.append("Thomas Hobbes")
    l.append("Thomas Jefferson")
    l.append("Tácito")
    l.append("Victor Hugo")
    l.append("Voltaire")
    l.append("William Shakespeare")
    l.append("William Somerset Maugham")
    l.append("Winston Churchill")
    l.append("Woody Allen")
    l.append("Ángel Ganivet")
    #for autor in l:
        #busqueda = autor.replace(" ", "%20")
        #url = "w/index.php?title=Especial%3ABuscar&profile=default&search="+busqueda+"&fulltext=Search&searchengineselect=mediawiki"
        #url = "w/api.php?format=xml&action=query&titles="+busqueda+"&prop=revisions&rvprop=content"
        #obtener_resultado(url)
    busqueda = "William Shakespeare".replace(" ", "%20")
    #busqueda = 
    url = "w/api.php?format=xml&action=query&titles="+busqueda+"&prop=revisions&rvprop=content"
    obtener_resultado(url)

base_url = 'http://es.wikipedia.org/'
test()


